- name: Update Package Cache (apt/Ubuntu)
  tags: always
  apt:
    update_cache: yes
  changed_when: false

- name: Install i3
  ansible.builtin.package:
    name:
      - i3
      - vim
      - rofi
      - i3lock
      - polybar
      - feh
      - imagemagick
      - picom
      - xorg
      - x11-xkb-utils
      - xfce4-terminal
      - git
      - parcellite
      - sddm
      - xserver-xorg
      - xserver-xorg-core
      - firefox
      - fonts-jetbrains-mono
      - pavucontrol
      - telegram-desktop
      - flameshot
    state: latest
