#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

force_color_promt=yes
alias ls='ls --color=auto'
alias ll='ls --color=auto -al'
alias gosw='cd ~/.local/share/StartWine/data/scripts'
alias sega='/home/alexander/SegaGames/dgen/bin_x86-64/dgen'
alias goau='cd /home/alexander/audioLex/qtAudioLex; source env/bin/activate'
PS1='\[\e[33m\]\u\[\e[31m\]@\[\e[32m\]\h:\W\[\e[37m\]$ '
alias vpn='cd ~/openvpn/; ./2openvpnconnect.sh'
